server:
  port: 9200
spring:
  application:
    name: zuul-9200


# 把微服务注册到Eureka上
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  # 指定实例名称，一般用微服务的名称
  instance:
    instance-id: ${spring.application.name}
    # 访问路径可以显示IP地址
    prefer-ip-address: true
    # 设置发送心跳间隔,默认是30秒，以下设置仅为测试用
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端最后一次接收到心跳的最大间隔，默认90秒，超时将删除该服务
    lease-expiration-duration-in-seconds: 2