server:
  port: 6602
spring:
  application:
    name: stream-consume
  cloud:
    # stream 配置
    stream:
      binders: # 要绑定的rabbitMQ服务器信息
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit  # 设置要绑定的消息服务的具体设置
          group: groupA # 设置分组，同一个分组是竞争关系，只有其中一个接收者可以消费







