server:
  port: 8200
spring:
  application:
    name: consul-consume-order
  could:
    # 服务注册进 consul
    consul:
      host: localhost
      port: 8500
      discovery:
        # 是否注册，默认是
        register: true
        #实例ID
        instance-id:  ${spring.application.name}:${spring.cloud.client.ipAddress}
        #服务实例名称
        service-name: ${spring.application.name}
        #服务实例端口
        port: ${server.port}
        #健康检查路径
        healthCheckPath: /actuator/health
        #健康检查时间间隔
        healthCheckInterval: 15s
        #开启ip地址注册
        prefer-ip-address: true
        #实例的请求ip
        ip-address: ${spring.cloud.client.ip-address}