server:
  port: 8501
spring:
  application:
    name: HystrixPayment
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka